version: '3.8'

networks:
  test-networks:
volumes:
  postgres_data:

services:
  db:
    container_name: db-test
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=db-test
    networks:
      - test-networks
  redis:
    container_name: redis
    image: redis:6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf